import {StyleSheet, Platform, Dimensions} from 'react-native';
import {size, family} from '../fonts';
import {colors} from '../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  circle: {
    width: 35,
    height: 35,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flex: {
    flex: 1,
  },
  thumbnailSty: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  txbold: {
    fontFamily: family.semibold,
  },
  borderStyle: {borderWidth: 1, borderColor: colors.grey},
  row: {flexDirection: 'row'},

  pd20: {padding: 20},
  pd40: {padding: 40},
  pd10: {padding: 10},
  pd_H10: {paddingHorizontal: 10},
  pdT0: {paddingTop: 0},
  pd_H20: {paddingHorizontal: 20},
  mt_v: {marginVertical: 10},
  mt_B: {marginBottom: 15},
  mt_B10: {marginBottom: 10},
  ml_15: {marginLeft: 10},
  mt_t10: {marginTop: 10},
  mt_t1: {marginTop: 1},
  mh_10: {marginHorizontal: 10},
  mr_10: {marginRight: 15},
  mt_50: {marginTop: '50%'},

  wdh60: {width: '60%'},
  wdh40: {width: '40%'},
  wdh20: {width: '20%'},
  wdh30: {width: '30%'},
  wdh10: {width: '10%'},
  wdh15: {width: '15%'},
  wdh55: {width: '55%'},
  wdh70: {width: '70%'},
  wdh50: {width: '50%'},
  wdh48: {width: '48%'},
  wdh80: {width: '80%'},
  wdh90: {width: '90%'},
  wdh65: {width: '65%'},
  wdh85: {width: '85%'},
  wdh45: {width: '45%'},
  mr30: {marginRight: '30%'},

  center: {justifyContent: 'center', alignItems: 'center', flex: 1},
  align_C: {alignItems: 'center'},
  align_E: {alignItems: 'flex-end'},
  justify_C: {justifyContent: 'center'},
  justify: {justifyContent: 'flex-end'},
  justify_S: {justifyContent: 'space-between'},
  justify_A: {justifyContent: 'space-around'},
  justify_E: {justifyContent: 'space-evenly'},

  txAlignC: {textAlign: 'center'},
  txAlignJ: {textAlign: 'justify'},
  txAlignR: {textAlign: 'right'},
  txAlignL: {textAlign: 'left'},

  txCap: {textTransform: 'capitalize'},
  txUpr: {textTransform: 'uppercase'},

  txDecor: {textDecorationLine: 'underline'},
  txColor: {
    color: colors.black,
  },
  tx10: {
    fontSize: 10,
    color: colors.black,
    fontFamily: family.regular,
  },
  tx12: {
    fontSize: size.label,
    color: colors.black,
    fontFamily: family.regular,
  },

  tx13: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
  },
  txradio: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
    // letterSpacing: 1,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  tx14No: {
    fontSize: 16,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  tx14: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx14_B: {
    fontSize: size.subtitle,
    color: colors.black,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  tx14_C: {
    fontSize: size.subtitle,
    fontFamily: family.semibold,
    textAlign: 'justify',
    letterSpacing: 0.6,
  },
  txlocation: {
    fontSize: size.location,
    color: colors.black,
    fontFamily: family.regular,
    textAlign: 'justify',
  },
  tx18: {
    fontSize: size.subheading,
    color: colors.black,
    fontFamily: family.medium,
    textAlign: 'justify',
  },
  tx16: {
    fontSize: size.title,
    color: colors.black,
    fontFamily: family.semibold,
    lineHeight: 24,
    letterSpacing: 0.3,
  },

  error: {
    color: colors.danger,
    fontSize: 12,
    marginLeft: 15,
  },

  btntxt: {
    fontSize: size.subtitle,
    color: colors.blue,
    fontFamily: family.medium,
    letterSpacing: 1,
    textAlign: 'center',
  },
  tx20: {
    fontSize: size.heading,
    color: colors.logogreen,
    fontFamily: family.bold,
  },

  txheading: {
    fontSize: size.title,
    color: colors.fontcolor,
    fontFamily: family.bold,
    fontStyle: 'italic',
    fontWeight: '800',
    letterSpacing: 1,
  },
  txheader: {
    fontSize: size.title,
    color: colors.white,
    fontFamily: family.medium,
  },
  tx22: {
    fontSize: 22,
    color: colors.black,
    fontFamily: family.medium,
  },
  logoSty: {
    width: 161,
    height: 76,
    resizeMode: 'contain',
  },

  box: {
    borderWidth: 1.5,
    borderColor: colors.grey,
    paddingHorizontal: 5,
    width: 125,
  },
  inputsty: {
    borderWidth: 1.5,
    borderColor: colors.grey,
    paddingHorizontal: 15,
    borderRadius: 8,
    width: '100%',
    height: 50,
    alignSelf: 'center',
    marginBottom: 8,
  },
  iconsty: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },

  picker_sty: {
    borderWidth: 1,
    borderColor: colors.grey,
    borderRadius: 8,
    marginTop: 5,
  },
  animatedCir_1: {
    // width: 135, height: 135,
    borderRadius: 13,
    borderWidth: 2,
    flexDirection: 'row',
    borderColor: colors.white,
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
    marginBottom: 5,
  },
  mybtn: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mybtnbene: {
    padding: 5,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    width: 190,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardsty: {
    backgroundColor: 'white',
    borderRadius: 10,
    paddingHorizontal: 25,
    width: '100%',
    borderWidth: 0.3,
    borderColor: '#AAA9A9',
    marginTop: -40,
    elevation: 1,
  },
  shadowProp: {
    shadowColor: colors.black,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 1,
    shadowRadius: 10,
  },

  option: {
    flex: 1,
    flexWrap: 'wrap',

    flexDirection: 'row',
  },
  draftBox: {
    marginTop: 10,
    borderLeftWidth: 20,
    padding: 15,
    margin: 6,
    borderRadius: 10,
    // borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    marginBottom: 10,
  },
  boxsty: {
    padding: 15,
    borderRadius: 10,
    borderColor: colors.grey,
    borderWidth: 0.5,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
    elevation: 1,
  },
  homeimage: {
    height: 38,
    width: 38,
    marginRight: 15,
  },
  checklistcard: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 15,
    borderWidth: 1,
    borderTopColor: colors.grey,
    borderBottomColor: colors.grey,
    borderLeftColor: colors.grey,
    marginVertical: 5,
  },
  checklistoptionContainer: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  headingtxt: {
    height: 42,
    width: 100,
    opacity: 0.9,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    borderRadius: 5,
    backgroundColor: colors.indian_red,
    margin: 1,
  },
  htxt: {
    textAlign: 'center',
    color: 'white',
    fontSize: 16,
    letterSpacing: 0.3,
  },
  disabledButton: {
    backgroundColor: colors.grey,
  },
  SyncStatusTextColor: {
    inprogess: colors.orange,
    completed: colors.green,
    error: colors.red,
  },
  privacyTxt: {
    fontSize: size.label,
    color: 'blue',
    fontFamily: family.regular,
    textDecorationLine: 'underline',
  },
});
