const colors = {
  danger: 'red',
  black: '#000',
  white: '#fff',
  skyblue: '#80CDDB',
  logogreen: '#37bd59',
  fontcolor: 'rgba(0, 102, 102, 1)',
  grey: '#ccc',
  yellow: '#FFFF00',
  lightText: '#777',
  blue: '#050448',
  red: '#AF0000',
  pink: '#EF5DA8',
  bcolor: '#ffffff',
  purple: '#AEAFF7',
  lightBlue: '#1A1881',
  orange: '#F09E54',
  footer_bg: '#020074',
  link: '#1F90A5',
  card_border: '#4FE3FE',
  drawerCircle: '#16A9B1A1',
  textBox: '#252836',
  dashboard_bg: '#14243E',
  circle_1: '#37bd59',
  circle_2: '#4A9CB9',
  warning: '#F8A435',
  frozy: '#D3FFF5',
  lightFrozy: '#02BD94',
  lightgrey: '#3E3E3E',

  //ni-app
  indian_red: '#A4353D',
  green: '#1A8525',
};

const images = {
  logoni: require('../../images/logoni.png'),
  menu: require('../../images/menu.png'),
  logo: require('../../images/logo.png'),
  SplashScreen: require('../../images/SplashScreen.png'),
  ANNAP: require('../../images/ANNAP.png'),
  VHSND: require('../../images/VHSND.png'),
  FACILITYV: require('../../images/FACILITYV.png'),
  WAJAND: require('../../images/WAJAND.png'),
  GODHB: require('../../images/GODHB.png'),
  BENEFICARIES_H2H_MONITORING: require('../../images/BENEFICARIES_H2H_MONITORING.png'),
  Nodatafound: require('../../images/Nodatafound.png'),
  BASELINE: require('../../images/BASELINE.png'),
  GALIDRAA: require('../../images/GALIDRAA.png'),
  SELF_ASSESSMENT_HINDI: require('../../images/FACILITYV.png'),
};

export {colors, images};
